version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db.uurnofauljwfceevleoo.supabase.co
      - DB_USER=postgres
      - DB_PASSWORD=saskia200314
      - DB_NAME=postgres
      - DB_PORT=5432
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: 